-- Insert sample Products into the Product table
INSERT INTO Product (id, name, category, price, stock) VALUES (1, 'Laptop', 'Electronics', 899.99, 50);
INSERT INTO Product (id, name, category, price, stock) VALUES (2, 'Wireless Mouse', 'Electronics', 29.99, 150);
INSERT INTO Product (id, name, category, price, stock) VALUES (3, 'USB-C Cable', 'Accessories', 12.99, 200);
INSERT INTO Product (id, name, category, price, stock) VALUES (4, 'Monitor 27"', 'Electronics', 299.99, 30);
INSERT INTO Product (id, name, category, price, stock) VALUES (5, 'Mechanical Keyboard', 'Electronics', 149.99, 75);
INSERT INTO Product (id, name, category, price, stock) VALUES (6, 'Laptop Stand', 'Accessories', 49.99, 100);
INSERT INTO Product (id, name, category, price, stock) VALUES (7, 'Headphones', 'Electronics', 199.99, 60);
INSERT INTO Product (id, name, category, price, stock) VALUES (8, 'Phone Case', 'Accessories', 19.99, 250);
INSERT INTO Product (id, name, category, price, stock) VALUES (9, 'USB Hub', 'Accessories', 39.99, 120);
INSERT INTO Product (id, name, category, price, stock) VALUES (10, 'Webcam 1080p', 'Electronics', 79.99, 45);
INSERT INTO Product (id, name, category, price, stock) VALUES (11, 'External SSD 1TB', 'Storage', 149.99, 80);
INSERT INTO Product (id, name, category, price, stock) VALUES (12, 'HDMI Cable', 'Accessories', 9.99, 300);
INSERT INTO Product (id, name, category, price, stock) VALUES (13, 'Desk Lamp', 'Furniture', 35.99, 90);
INSERT INTO Product (id, name, category, price, stock) VALUES (14, 'Wireless Charger', 'Electronics', 24.99, 180);
INSERT INTO Product (id, name, category, price, stock) VALUES (15, 'Phone Screen Protector', 'Accessories', 7.99, 400);
INSERT INTO Product (id, name, category, price, stock) VALUES (16, 'Tablet', 'Electronics', 449.99, 35);
INSERT INTO Product (id, name, category, price, stock) VALUES (17, 'Stylus Pen', 'Accessories', 45.99, 110);
INSERT INTO Product (id, name, category, price, stock) VALUES (18, 'Portable Speaker', 'Electronics', 59.99, 70);
INSERT INTO Product (id, name, category, price, stock) VALUES (19, 'Phone Stand', 'Accessories', 14.99, 220);
INSERT INTO Product (id, name, category, price, stock) VALUES (20, 'Screen Cleaning Kit', 'Accessories', 12.99, 160);
INSERT INTO Product (id, name, category, price, stock) VALUES (21, 'Cooling Pad', 'Electronics', 35.99, 85);
INSERT INTO Product (id, name, category, price, stock) VALUES (22, 'Desk Organizer', 'Furniture', 29.99, 125);
INSERT INTO Product (id, name, category, price, stock) VALUES (23, 'USB Flash Drive 64GB', 'Storage', 19.99, 200);
INSERT INTO Product (id, name, category, price, stock) VALUES (24, 'HDMI Splitter', 'Accessories', 21.99, 95);
INSERT INTO Product (id, name, category, price, stock) VALUES (25, 'Document Camera', 'Electronics', 199.99, 25);
INSERT INTO Product (id, name, category, price, stock) VALUES (26, 'Keyboard Switch Puller', 'Accessories', 8.99, 150);
INSERT INTO Product (id, name, category, price, stock) VALUES (27, 'Monitor Arm Mount', 'Furniture', 59.99, 55);
INSERT INTO Product (id, name, category, price, stock) VALUES (28, 'Microphone Stand', 'Accessories', 19.99, 140);
INSERT INTO Product (id, name, category, price, stock) VALUES (29, 'RGB LED Strip', 'Electronics', 29.99, 110);
INSERT INTO Product (id, name, category, price, stock) VALUES (30, 'Cable Management Set', 'Accessories', 15.99, 180);
INSERT INTO Product (id, name, category, price, stock) VALUES (31, 'Desk Mat', 'Furniture', 24.99, 170);
INSERT INTO Product (id, name, category, price, stock) VALUES (32, 'Power Bank 20000mAh', 'Electronics', 49.99, 90);
INSERT INTO Product (id, name, category, price, stock) VALUES (33, 'USB Extension Cable', 'Accessories', 11.99, 250);
INSERT INTO Product (id, name, category, price, stock) VALUES (34, 'Laptop Backpack', 'Accessories', 59.99, 65);
INSERT INTO Product (id, name, category, price, stock) VALUES (35, 'Gaming Mouse Pad', 'Accessories', 22.99, 130);
INSERT INTO Product (id, name, category, price, stock) VALUES (36, 'Thunderbolt Cable', 'Accessories', 34.99, 75);
INSERT INTO Product (id, name, category, price, stock) VALUES (37, 'Monitor Light Bar', 'Electronics', 99.99, 40);
INSERT INTO Product (id, name, category, price, stock) VALUES (38, 'Laptop Cooling Stand', 'Furniture', 45.99, 85);
INSERT INTO Product (id, name, category, price, stock) VALUES (39, 'USB-A to USB-C Adapter', 'Accessories', 13.99, 220);
INSERT INTO Product (id, name, category, price, stock) VALUES (40, 'Docking Station', 'Electronics', 149.99, 50);
INSERT INTO Product (id, name, category, price, stock) VALUES (41, 'Keyboard Wrist Rest', 'Accessories', 18.99, 160);
INSERT INTO Product (id, name, category, price, stock) VALUES (42, 'Monitor Screen Cleaner', 'Accessories', 9.99, 280);
INSERT INTO Product (id, name, category, price, stock) VALUES (43, 'Wireless Keyboard Mouse Combo', 'Electronics', 69.99, 95);
INSERT INTO Product (id, name, category, price, stock) VALUES (44, 'Desk Chair Mat', 'Furniture', 39.99, 110);
INSERT INTO Product (id, name, category, price, stock) VALUES (45, 'USB Extension Hub', 'Accessories', 32.99, 140);
INSERT INTO Product (id, name, category, price, stock) VALUES (46, '4K Webcam', 'Electronics', 129.99, 35);
INSERT INTO Product (id, name, category, price, stock) VALUES (47, 'Laptop Privacy Screen', 'Accessories', 44.99, 75);
INSERT INTO Product (id, name, category, price, stock) VALUES (48, 'Desk Organizer with Drawer', 'Furniture', 54.99, 60);
INSERT INTO Product (id, name, category, price, stock) VALUES (49, 'Portable Monitor 15.6"', 'Electronics', 249.99, 28);
INSERT INTO Product (id, name, category, price, stock) VALUES (50, 'Ergonomic Mouse Pad with Wrist Support', 'Accessories', 26.99, 145);